resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/feature/decrease_size
    
jobs:
- job: Windows_Build
  displayName: Build on Windows
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
  - task: PowerShell@2
    displayName: Build
    inputs:
      filePath: build.ps1
      arguments: Quick --configuration Release
      failOnStderr: true
  - task: CopyFiles@2
    displayName: Copy net472 Build to $(Build.ArtifactStagingDirectory)
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\artifacts\package\
      Contents: >-
        **\omnisharp-net472.zip

        **\omnisharp-net472.tar.gz
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: build'
    inputs:
      ArtifactName: omnisharp-472
- job: Linux_Build
  displayName: Build on Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
  - task: PowerShell@2
    displayName: Build
    inputs:
      filePath: build.sh
      arguments: --target Quick --configuration Release
      failOnStderr: true
  - task: CopyFiles@2
    displayName: Copy Build to $(Build.ArtifactStagingDirectory)
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\artifacts\package\
      Contents: >-
        **\omnisharp-net6.0.zip

        **\omnisharp-net6.0.tar.gz
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: build'
    inputs:
      ArtifactName: omnisharp-ubuntu
...
